<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVsCqlYA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVsCqlYA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVsCqlYA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVsCqlYA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVsCqlYA\App_KernelDevDebugContainer([
    'container.build_hash' => 'VsCqlYA',
    'container.build_id' => '3c178da6',
    'container.build_time' => 1591706754,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVsCqlYA');
