<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'cart' => [[], ['_controller' => 'App\\Controller\\MainController::cartlist'], [], [['text', '/cart']], [], []],
    'add_to_cart' => [[], ['_controller' => 'App\\Controller\\MainController::add'], [], [['text', '/add']], [], []],
    'remove_from_cart' => [[], ['_controller' => 'App\\Controller\\MainController::remove'], [], [['text', '/remove']], [], []],
    'payement_eligibility' => [[], ['_controller' => 'App\\Controller\\MainController::check'], [], [['text', '/payement_eligibility']], [], []],
    'payement' => [[], ['_controller' => 'App\\Controller\\MainController::payement'], [], [['text', '/payement']], [], []],
    'thankyou' => [[], ['_controller' => 'App\\Controller\\MainController::thankyou'], [], [['text', '/confirm-order']], [], []],
];
